# Generated by Django 3.1.3 on 2020-11-14 06:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('visitas', '0002_auto_20201113_2339'),
    ]

    operations = [
        migrations.RenameField(
            model_name='registroactividade',
            old_name='activiti',
            new_name='actividad',
        ),
    ]
