# Generated by Django 3.1.3 on 2020-11-14 06:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('visitas', '0003_auto_20201114_0005'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='visita',
            new_name='RegistrarVisita',
        ),
    ]
