# Generated by Django 3.1.3 on 2020-11-14 06:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('visitas', '0004_auto_20201114_0008'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Registroactividade',
            new_name='RegistrarActividade',
        ),
    ]
