# Generated by Django 3.1.3 on 2020-11-14 06:13

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('visitas', '0005_auto_20201114_0010'),
    ]

    operations = [
        migrations.CreateModel(
            name='sexo',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('descripcion', models.CharField(max_length=1)),
            ],
        ),
        migrations.AlterField(
            model_name='registrarvisita',
            name='Sexo',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='visitas.sexo'),
        ),
    ]
